# Auto-generated using compose2nix v0.3.3-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."gotosocial" = {
    image = "superseriousbusiness/gotosocial:latest";
    volumes = [
      "/home/leah/gotosocial/config.yaml:/gotosocial/config.yaml:rw"
      "/home/leah/gotosocial/data:/gotosocial/storage:rw"
    ];
    ports = [
      "0.0.0.0:8080:8080/tcp"
    ];
    cmd = [ "--config-path" "/gotosocial/config.yaml" ];
    dependsOn = [
      "gotosocial_postgres"
    ];
    user = "1000:1000";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=gotosocial"
      "--network=gotosocial_gotosocial"
    ];
  };
  systemd.services."podman-gotosocial" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-gotosocial_gotosocial.service"
    ];
    requires = [
      "podman-network-gotosocial_gotosocial.service"
    ];
    partOf = [
      "podman-compose-gotosocial-root.target"
    ];
    wantedBy = [
      "podman-compose-gotosocial-root.target"
    ];
  };
  virtualisation.oci-containers.containers."gotosocial_postgres" = {
    image = "postgres:16";
    environment = {
      "POSTGRES_DB" = "gotosocial";
      "POSTGRES_PASSWORD" = "w5sy2XLDkfHqAYrPTQJjK8";
      "POSTGRES_USER" = "gotosocial";
    };
    volumes = [
      "/root/gotosocial/postgres:/var/lib/postgresql/data:rw"
    ];
    ports = [
      "127.0.0.1:5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=gotosocial_postgres"
      "--network-alias=postgres"
      "--network=gotosocial_gotosocial"
    ];
  };
  systemd.services."podman-gotosocial_postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-gotosocial_gotosocial.service"
    ];
    requires = [
      "podman-network-gotosocial_gotosocial.service"
    ];
    partOf = [
      "podman-compose-gotosocial-root.target"
    ];
    wantedBy = [
      "podman-compose-gotosocial-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-gotosocial_gotosocial" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f gotosocial_gotosocial";
    };
    script = ''
      podman network inspect gotosocial_gotosocial || podman network create gotosocial_gotosocial --subnet=172.21.0.0/16 --gateway=172.21.0.1
    '';
    partOf = [ "podman-compose-gotosocial-root.target" ];
    wantedBy = [ "podman-compose-gotosocial-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-gotosocial-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
