# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."imagetool_db" = {
    image = "postgres:latest";
    environment = {
      "POSTGRES_DB" = "imagetool_development";
      "POSTGRES_PASSWORD" = "password";
      "POSTGRES_USER" = "imagetool";
    };
    volumes = [
      "imagetool_postgresdata:/home/leah/documents/data/photo_project/postgres:rw"
    ];
    ports = [
      "54321:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=imagetool_db"
      "--network-alias=db"
      "--network=imagetool_default"
    ];
  };
  systemd.services."podman-imagetool_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-imagetool_default.service"
      "podman-volume-imagetool_postgresdata.service"
    ];
    requires = [
      "podman-network-imagetool_default.service"
      "podman-volume-imagetool_postgresdata.service"
    ];
    partOf = [
      "podman-compose-imagetool-root.target"
    ];
    wantedBy = [
      "podman-compose-imagetool-root.target"
    ];
  };
  virtualisation.oci-containers.containers."redis" = {
    image = "redis:latest";
    volumes = [
      "imagetool_redisdata:/home/leah/documents/data/photo_project/redis:rw"
    ];
    ports = [
      "6379:6379/tcp"
    ];
    cmd = [ "redis-server" "--save" "60" "1" "--loglevel" "warning" ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=redis"
      "--network-alias=redis"
      "--network=imagetool_default"
    ];
  };
  systemd.services."podman-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-imagetool_default.service"
      "podman-volume-imagetool_redisdata.service"
    ];
    requires = [
      "podman-network-imagetool_default.service"
      "podman-volume-imagetool_redisdata.service"
    ];
    partOf = [
      "podman-compose-imagetool-root.target"
    ];
    wantedBy = [
      "podman-compose-imagetool-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-imagetool_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f imagetool_default";
    };
    script = ''
      podman network inspect imagetool_default || podman network create imagetool_default
    '';
    partOf = [ "podman-compose-imagetool-root.target" ];
    wantedBy = [ "podman-compose-imagetool-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-imagetool_postgresdata" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect imagetool_postgresdata || podman volume create imagetool_postgresdata
    '';
    partOf = [ "podman-compose-imagetool-root.target" ];
    wantedBy = [ "podman-compose-imagetool-root.target" ];
  };
  systemd.services."podman-volume-imagetool_redisdata" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect imagetool_redisdata || podman volume create imagetool_redisdata
    '';
    partOf = [ "podman-compose-imagetool-root.target" ];
    wantedBy = [ "podman-compose-imagetool-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-imagetool-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}

